name: build-and-push

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'training/**'
      - '.github/workflows/build.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_API: ghcr.io/hamodikk/gemstone-mini-api
      IMAGE_TRAINER: ghcr.io/hamodikk/gemstone-mini-trainer

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

      # If you have a trainer image, keep this; otherwise delete this step
      - name: Build & push TRAINER
        uses: docker/build-push-action@v6
        with:
          context: ./training
          push: true
          tags: |
            ${{ env.IMAGE_TRAINER }}:latest
            ${{ env.IMAGE_TRAINER }}:${{ github.sha }}
